"""added userinfo, find definition statistic

Revision ID: 122feefadc11
Revises: 72eefbd101cc
Create Date: 2023-08-02 07:58:28.216264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122feefadc11'
down_revision = '72eefbd101cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_info_user_id_fkey', 'user_info', type_='foreignkey')
    op.drop_column('user_info', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_info_user_id_fkey', 'user_info', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
