"""added userinfo, find definition statistic

Revision ID: 72eefbd101cc
Revises: 7757f7d3165c
Create Date: 2023-08-02 03:48:16.739439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72eefbd101cc'
down_revision = '7757f7d3165c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_info', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_info', type_='foreignkey')
    op.drop_column('user_info', 'user_id')
    # ### end Alembic commands ###
