"""added userinfo, find definition statistic

Revision ID: 7757f7d3165c
Revises: 677f3860e9bd
Create Date: 2023-08-02 03:39:05.241945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7757f7d3165c'
down_revision = '677f3860e9bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('find_definition_statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('win_guesses', sa.Integer(), nullable=False),
    sa.Column('lose_guesses', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('collection_name_key', 'collection', type_='unique')
    op.create_unique_constraint('unique_collection_in_folder', 'collection', ['name', 'folder_id'])
    op.drop_constraint('collection_owner_id_fkey', 'collection', type_='foreignkey')
    op.drop_constraint('collection_folder_id_fkey', 'collection', type_='foreignkey')
    op.create_foreign_key(None, 'collection', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'collection', 'folder', ['folder_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('folder_name_key', 'folder', type_='unique')
    op.create_unique_constraint('unique_folder_in_folder', 'folder', ['name', 'parent_folder_id'])
    op.drop_constraint('folder_owner_id_fkey', 'folder', type_='foreignkey')
    op.drop_constraint('folder_parent_folder_id_fkey', 'folder', type_='foreignkey')
    op.create_foreign_key(None, 'folder', 'folder', ['parent_folder_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'folder', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('unique_term_in_collection', 'term', ['name', 'collection_id'])
    op.drop_constraint('term_collection_id_fkey', 'term', type_='foreignkey')
    op.drop_constraint('term_owner_id_fkey', 'term', type_='foreignkey')
    op.create_foreign_key(None, 'term', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'term', 'collection', ['collection_id'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('user_info_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['telegram_id'])
    op.create_foreign_key(None, 'user', 'user_info', ['user_info_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_info_id')
    op.drop_constraint(None, 'term', type_='foreignkey')
    op.drop_constraint(None, 'term', type_='foreignkey')
    op.create_foreign_key('term_owner_id_fkey', 'term', 'user', ['owner_id'], ['id'])
    op.create_foreign_key('term_collection_id_fkey', 'term', 'collection', ['collection_id'], ['id'])
    op.drop_constraint('unique_term_in_collection', 'term', type_='unique')
    op.drop_constraint(None, 'folder', type_='foreignkey')
    op.drop_constraint(None, 'folder', type_='foreignkey')
    op.create_foreign_key('folder_parent_folder_id_fkey', 'folder', 'folder', ['parent_folder_id'], ['id'])
    op.create_foreign_key('folder_owner_id_fkey', 'folder', 'user', ['owner_id'], ['id'])
    op.drop_constraint('unique_folder_in_folder', 'folder', type_='unique')
    op.create_unique_constraint('folder_name_key', 'folder', ['name'])
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.create_foreign_key('collection_folder_id_fkey', 'collection', 'folder', ['folder_id'], ['id'])
    op.create_foreign_key('collection_owner_id_fkey', 'collection', 'user', ['owner_id'], ['id'])
    op.drop_constraint('unique_collection_in_folder', 'collection', type_='unique')
    op.create_unique_constraint('collection_name_key', 'collection', ['name'])
    op.drop_table('find_definition_statistic')
    op.drop_table('user_info')
    # ### end Alembic commands ###
