# syntax=docker/dockerfile:1
FROM python:3.11-alpine
RUN apk add --no-cache postgresql-dev gcc python3-dev musl-dev
WORKDIR /code
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY bot ./bot
COPY database ./database
COPY config.py config.py
