"""File with constans for bot app
"""

MAX_TERM_NAME_LENGTH = 128
MAX_TERM_DEFINITION_LENGTH = 256
MIN_TERMS_COUNT_SIMPLE_TRAIN = 1
PERMANENT_SAVED_KEYS_IN_STATE = ['locale', ]
LOCALES_LIST = ['en', 'ru']
DEFAULT_LOCALE = 'en'
MIN_TERMS_COUNT_SIMPLE_TRAIN = 1
MAX_ITEMS_PAGE_BROWSE_FOLDERS = 8
MAX_ITEMS_PAGE_BROWSE_COLLECTIONS = 8
MAX_ITEMS_PAGE_BROWSE_TERMS = 8
FIND_DEFINITION_POLL_TIME = 10
MIN_TERMS_COUNT_FIND_DEFINITION = FIND_DEFINITION_LIMIT_OF_OPTIONS = 4
